/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.inf.symod.fm023.homework;

/**
* Interface for state machines which use timed event triggers.
*/
public interface ITimerCallback {
	
	/**
	* Callback method if a time event occurred.
	* 
	* @param eventID
	* 			:The id of the occurred event.
	*/
	public void timeElapsed(int eventID);
}
